### ISSUE TITLE
Formatting does not work

### ISSUE THREAD

**Issue by benonymus** [vincens2005/lite-formatters#11]
Hey,

I added this plugin to my lite-xl install. 
When I format either by calling the command directly or save on format, I get log that the formatting was triggered, but I don't see the changes in the file.

I even poked around and logged out the formatting command.Iif I run that in my terminal it works.

The issue is on an apple silicon mac.
Any idea what could it be?

**Comment by benonymus** [comment]
I tried it on windows, there is works nicely. Even the elixir formatter I just made.

**Comment by tobip** [comment]
Same here on linux:
Log says `formatting (filename.html) with HTML Beautifier` - but no changes appear in the editor.
Is there a way to get more logs out of it?

**Comment by kmafeni04** [comment]
Do you have the specific formatters installed?

**Comment by sebkolind** [comment]
Same thing happens for me.

**Comment by PerilousBooklet** [comment]
@benonymus You should also specify which formatter module you're using and for which language, to make it easier for us to help you.
If you no longer have this problem, please close this issue.

**Comment by benonymus** [comment]
I was trying elixir. I am not using lite anymore. I will close the issue.
