### ISSUE TITLE
Issues formatting 

### ISSUE THREAD

**Issue by kmafeni04** [vincens2005/lite-formatters#16]
the log:

Mon Sep 25 23:25:44 2023 [ERROR] /home/kome/.config/pragtical/plugins/formatter.lua:64: attempt to concatenate local 'filename' (a nil value) at /usr/share/pragtical/core/init.lua:1069

stack traceback:
/home/kome/.config/pragtical/plugins/formatter.lua:64: in function 'perform'
/usr/share/pragtical/core/command.lua:144: in function </usr/share/pragtical/core/command.lua:137>
[C]: in function 'xpcall'
/usr/share/pragtical/core/init.lua:1068: in function 'try'
/usr/share/pragtical/core/command.lua:169: in function 'perform'
/usr/share/pragtical/core/keymap.lua:230: in function 'on_key_pressed'
/usr/share/pragtical/core/init.lua:1086: in function 'on_event'
/usr/share/pragtical/plugins/macro.lua:19: in function </usr/share/pragtical/plugins/macro.lua:18>
[C]: in function 'xpcall'
/usr/share/pragtical/core/init.lua:1068: in function 'try'
/usr/share/pragtical/core/init.lua:1178: in function 'step'
/usr/share/pragtical/core/init.lua:1301: in function 'core_run'
/usr/share/pragtical/plugins/settings.lua:1914: in function 'core_run'
/usr/share/pragtical/plugins/ipc.lua:852: in function 'core_run'
/home/kome/.config/pragtical/plugins/recentfiles.lua:77: in function 'run'
[string "local core..."]:15: in function <[string "local core..."]:6>
[C]: in function 'xpcall'
[string "local core..."]:6: in main chunk

I'm using pragtical which is a fork of lite xl but I'm not all that sure it's a pragtical plugin since they maintain coherence as much as possible to the lite xl project

**Comment by PerilousBooklet** [comment]
If you're using pragctical you should ask on their `formatter` repo, [here](https://github.com/pragtical/formatter/issues) instead of this one.

**Comment by PerilousBooklet** [comment]
Also @vincens2005, this issue should be closed now.
